name: AntiCooldown-Beta
version: 53
api-version: 1.14
softdepend: [TubeTils]
main: com.yourgamespace.anticooldown.beta.main.Main
commands:
  anticooldown:
    usage: </command>
    aliases: [ac]